/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Discover Memory
         * @deprecated
         * @description Legacy v1.0 full-pipeline adapter retained during the migration window.
         */
        post: operations["discover_memory_v1_memories_discover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/discover-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Discover History
         * @description Rank historical candidates deterministically without model calls.
         */
        post: operations["discover_history_v1_memories_discover_history_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Memory
         * @description Expand a reviewed candidate into perspectives and a grounded quest.
         */
        post: operations["generate_memory_v1_memories_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/generate-stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Memory Stream
         * @description Expose the canonical generation result as newline-delimited stage events.
         */
        post: operations["generate_memory_stream_v1_memories_generate_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CandidateScoreBreakdown
         * @description Weighted eligibility contributions; total excludes the ranking-only penalty.
         */
        CandidateScoreBreakdown: {
            /**
             * Diversity Penalty
             * @default 0
             */
            diversity_penalty: number;
            /** Evidence Strength */
            evidence_strength: number;
            /** Human Signals */
            human_signals: number;
            /** Resurfacing Relevance */
            resurfacing_relevance: number;
            /** Squad Specificity */
            squad_specificity: number;
            /** Total */
            total: number;
        };
        /** CurrentContext */
        CurrentContext: {
            /** Active Member Ids */
            active_member_ids?: string[];
            /**
             * Original Mode Available
             * @default true
             */
            original_mode_available: boolean;
            /** Resurfacing Reason */
            resurfacing_reason?: string | null;
        };
        /** DiscoveryAssessment */
        DiscoveryAssessment: {
            /** Eligible */
            eligible: boolean;
            /** Reasons */
            reasons: string[];
            /** Signal Score */
            signal_score: number;
            /** Threshold */
            threshold: number;
        };
        /** EvidenceRef */
        EvidenceRef: {
            /** Event Id */
            event_id: string;
            /** Event Type */
            event_type: string;
            /** Significance */
            significance: string;
        };
        /** GenerateMemoryRequest */
        GenerateMemoryRequest: {
            /** Memory Pack */
            memory_pack: components["schemas"]["MemoryPack"] | components["schemas"]["MemoryPackV11"];
            /**
             * Schema Version
             * @default 1.1
             * @constant
             */
            schema_version: "1.1";
        };
        /**
         * GenerateStreamErrorEvent
         * @description A safe provider failure emitted after an NDJSON stream has begun.
         */
        GenerateStreamErrorEvent: {
            /** Code */
            code: string;
            /** Retryable */
            retryable: boolean;
            /** Stage */
            stage: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "error";
        };
        /**
         * GenerateStreamResultEvent
         * @description The canonical v1.1 result emitted as the final NDJSON record.
         */
        GenerateStreamResultEvent: {
            result: components["schemas"]["MemoryEngineResultV11"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "result";
        };
        /**
         * GenerateStreamStageEvent
         * @description One progress snapshot in the NDJSON generation stream.
         */
        GenerateStreamStageEvent: {
            /** Message */
            message?: string | null;
            /** Preview */
            preview?: components["schemas"]["MemoryRecord"] | components["schemas"]["PlayerPerspective"][] | components["schemas"]["NextChapter"] | components["schemas"]["ValidationReport"] | null;
            /**
             * Stage
             * @enum {string}
             */
            stage: "review_and_discovery" | "memory_discovery" | "perspectives" | "quest_generation" | "validation";
            /**
             * Status
             * @enum {string}
             */
            status: "working" | "complete" | "stopped" | "failed";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "stage";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoricalCandidate */
        HistoricalCandidate: {
            /** Match Id */
            match_id: string;
            meaning_status: components["schemas"]["MeaningStatus"];
            memory_type: components["schemas"]["MemoryType"];
            /** Pack Id */
            pack_id: string;
            /** Rank */
            rank: number;
            /** Ranking Score */
            ranking_score: number;
            /** Reasons */
            reasons: string[];
            /** Redactions */
            redactions?: components["schemas"]["RedactionNotice"][];
            /** Score */
            score: number;
            score_breakdown: components["schemas"]["CandidateScoreBreakdown"];
            source_status: components["schemas"]["SourceStatus"];
            /** Summary */
            summary: string;
            /** Title */
            title: string;
        };
        /** HistoricalDiscoveryRequest */
        HistoricalDiscoveryRequest: {
            /**
             * Limit
             * @default 3
             */
            limit: number;
            /** Memory Packs */
            memory_packs: (components["schemas"]["MemoryPack"] | components["schemas"]["MemoryPackV11"])[];
            /**
             * Schema Version
             * @default 1.1
             * @constant
             */
            schema_version: "1.1";
        };
        /** HistoricalDiscoveryResponse */
        HistoricalDiscoveryResponse: {
            /** Candidates */
            candidates: components["schemas"]["HistoricalCandidate"][];
            filters: components["schemas"]["HistoricalFilterCounts"];
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Schema Version
             * @default 1.1
             * @constant
             */
            schema_version: "1.1";
        };
        /** HistoricalFilterCounts */
        HistoricalFilterCounts: {
            /** Below Threshold */
            below_threshold: number;
            /** Dismissed */
            dismissed: number;
            /** Disputed */
            disputed: number;
            /** Duplicates Removed */
            duplicates_removed: number;
            /** Eligible Not Selected */
            eligible_not_selected: number;
            /** Insufficient Opted In */
            insufficient_opted_in: number;
            /** No Grounded Events */
            no_grounded_events: number;
            /** Received */
            received: number;
            /** Target Opted Out */
            target_opted_out: number;
        };
        /** HumanMemory */
        HumanMemory: {
            /** Author Player Id */
            author_player_id?: string | null;
            /** Caption */
            caption?: string | null;
            /** Confirmed */
            confirmed?: boolean | null;
            /** Tags */
            tags?: string[];
        };
        /** HumanMemoryV11 */
        HumanMemoryV11: {
            /** Author Player Id */
            author_player_id?: string | null;
            /** Caption */
            caption?: string | null;
            /** Tags */
            tags?: string[];
        };
        /**
         * HumanReview
         * @description Separate factual verification from a player's emotional judgment.
         */
        HumanReview: {
            /** @default unreviewed */
            meaning_status: components["schemas"]["MeaningStatus"];
            /** @default unreviewed */
            source_status: components["schemas"]["SourceStatus"];
        };
        /**
         * Importance
         * @enum {string}
         */
        Importance: "low" | "medium" | "high";
        /**
         * IssueSeverity
         * @enum {string}
         */
        IssueSeverity: "info" | "warning" | "error";
        /**
         * LegacyMemoryPack
         * @description The deprecated endpoint accepts only the original v1.0 wire contract.
         */
        LegacyMemoryPack: {
            current_context?: components["schemas"]["CurrentContext"];
            human_memory?: components["schemas"]["HumanMemory"] | null;
            match: components["schemas"]["MatchContext"];
            /** Match Events */
            match_events?: components["schemas"]["MatchEvent"][];
            /** Pack Id */
            pack_id: string;
            player_profile: components["schemas"]["PlayerProfile"];
            reactions?: components["schemas"]["Reactions"];
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            squad: components["schemas"]["LegacySquad"];
        };
        /**
         * LegacySquad
         * @description The legacy wire shape with current consent made explicit.
         */
        LegacySquad: {
            /** Days Since Full Squad */
            days_since_full_squad?: number | null;
            /** Matches Together */
            matches_together: number;
            /** Members */
            members: components["schemas"]["LegacySquadMember"][];
            /** Squad Id */
            squad_id: string;
        };
        /**
         * LegacySquadMember
         * @description A v1.0 member submitted through the public compatibility endpoint.
         */
        LegacySquadMember: {
            /** Display Name */
            display_name: string;
            /** Opted In */
            opted_in: boolean;
            /** Player Id */
            player_id: string;
            /** Role */
            role?: string | null;
        };
        /** MatchContext */
        MatchContext: {
            /** Map Name */
            map_name?: string | null;
            /** Match Id */
            match_id: string;
            /** Mode */
            mode: string;
            /** Placement */
            placement?: number | null;
            /** Played At */
            played_at?: string | null;
        };
        /** MatchEvent */
        MatchEvent: {
            /** Actor Id */
            actor_id?: string | null;
            /** Details */
            details?: {
                [key: string]: string | number | boolean;
            };
            /** Event Id */
            event_id: string;
            /** @default medium */
            importance: components["schemas"]["Importance"];
            /** Location */
            location?: string | null;
            /** Target Id */
            target_id?: string | null;
            /** Timestamp Seconds */
            timestamp_seconds?: number | null;
            /** Type */
            type: string;
        };
        /**
         * MeaningStatus
         * @enum {string}
         */
        MeaningStatus: "unreviewed" | "confirmed" | "dismissed";
        /** MemoryEngineResult */
        MemoryEngineResult: {
            discovery: components["schemas"]["DiscoveryAssessment"];
            memory?: components["schemas"]["MemoryRecord"] | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            next_chapter?: components["schemas"]["NextChapter"] | null;
            /** Pack Id */
            pack_id: string;
            /** Player Perspectives */
            player_perspectives?: components["schemas"]["PlayerPerspective"][];
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            status: components["schemas"]["PipelineStatus"];
            validation: components["schemas"]["ValidationReport"];
        };
        /** MemoryEngineResultV11 */
        MemoryEngineResultV11: {
            discovery: components["schemas"]["DiscoveryAssessment"];
            meaning_status: components["schemas"]["MeaningStatus"];
            memory?: components["schemas"]["MemoryRecord"] | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            next_chapter?: components["schemas"]["NextChapter"] | null;
            /** Pack Id */
            pack_id: string;
            /** Player Perspectives */
            player_perspectives?: components["schemas"]["PlayerPerspective"][];
            /**
             * Schema Version
             * @default 1.1
             * @constant
             */
            schema_version: "1.1";
            source_status: components["schemas"]["SourceStatus"];
            status: components["schemas"]["PipelineStatusV11"];
            validation: components["schemas"]["ValidationReport"];
        };
        /**
         * MemoryPack
         * @description Garena-style input: gameplay, social, human, and current context signals.
         */
        MemoryPack: {
            current_context?: components["schemas"]["CurrentContext"];
            human_memory?: components["schemas"]["HumanMemory"] | null;
            match: components["schemas"]["MatchContext"];
            /** Match Events */
            match_events?: components["schemas"]["MatchEvent"][];
            /** Pack Id */
            pack_id: string;
            player_profile: components["schemas"]["PlayerProfile"];
            reactions?: components["schemas"]["Reactions"];
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            squad: components["schemas"]["Squad"];
        };
        /**
         * MemoryPackV11
         * @description Canonical Phase 2 input with explicit consent and split review state.
         */
        MemoryPackV11: {
            current_context?: components["schemas"]["CurrentContext"];
            human_memory?: components["schemas"]["HumanMemoryV11"] | null;
            human_review: components["schemas"]["HumanReview"];
            match: components["schemas"]["MatchContext"];
            /** Match Events */
            match_events?: components["schemas"]["MatchEvent"][];
            /** Pack Id */
            pack_id: string;
            player_profile: components["schemas"]["PlayerProfile"];
            reactions?: components["schemas"]["Reactions"];
            /**
             * Schema Version
             * @default 1.1
             * @constant
             */
            schema_version: "1.1";
            squad: components["schemas"]["SquadV11"];
        };
        /** MemoryRecord */
        MemoryRecord: {
            /** Confidence */
            confidence: number;
            /** Evidence */
            evidence: components["schemas"]["EvidenceRef"][];
            /** Human Confirmed */
            human_confirmed: boolean;
            memory_type: components["schemas"]["MemoryType"];
            /** Summary */
            summary: string;
            /** Title */
            title: string;
        };
        /**
         * MemoryType
         * @enum {string}
         */
        MemoryType: "chaos" | "comeback" | "clutch" | "ritual" | "first" | "other";
        /** NextChapter */
        NextChapter: {
            /** Mission */
            mission: string;
            /** Objectives */
            objectives: components["schemas"]["QuestObjective"][];
            recipe: components["schemas"]["QuestRecipe"];
            /** Title */
            title: string;
        };
        /**
         * PipelineStatus
         * @enum {string}
         */
        PipelineStatus: "ready" | "needs_human_confirmation" | "rejected";
        /**
         * PipelineStatusV11
         * @enum {string}
         */
        PipelineStatusV11: "ready" | "needs_source_verification" | "needs_meaning_confirmation" | "rejected";
        /** PlayerPerspective */
        PlayerPerspective: {
            /** Display Name */
            display_name: string;
            /** Evidence Event Ids */
            evidence_event_ids: string[];
            /** Message */
            message: string;
            /** Player Id */
            player_id: string;
        };
        /** PlayerProfile */
        PlayerProfile: {
            /** Player Id */
            player_id: string;
            /** Preferred Role */
            preferred_role?: string | null;
        };
        /** ProviderErrorBody */
        ProviderErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Retryable */
            retryable: boolean;
            /** Stage */
            stage: string;
        };
        /** QualityScores */
        QualityScores: {
            /** Evidence Grounding */
            evidence_grounding: number;
            /** Perspective Distinctness */
            perspective_distinctness: number;
            /** Quest Connection */
            quest_connection: number;
            /** Specificity */
            specificity: number;
        };
        /** QuestObjective */
        QuestObjective: {
            /** Assigned Player Id */
            assigned_player_id?: string | null;
            /** Description */
            description: string;
            /** Objective Id */
            objective_id: string;
            /**
             * Required
             * @default true
             */
            required: boolean;
            /** Source Event Ids */
            source_event_ids: string[];
            verification: components["schemas"]["VerificationRule"];
        };
        /**
         * QuestRecipe
         * @enum {string}
         */
        QuestRecipe: "recreate" | "remix" | "resolve";
        /** Reactions */
        Reactions: {
            /**
             * Fire Count
             * @default 0
             */
            fire_count: number;
            /**
             * Laugh Count
             * @default 0
             */
            laugh_count: number;
            /**
             * Saved
             * @default false
             */
            saved: boolean;
        };
        /** RedactionNotice */
        RedactionNotice: {
            /** Alias */
            alias: string;
            /**
             * Reason
             * @default player_opted_out
             * @constant
             */
            reason: "player_opted_out";
        };
        /**
         * SourceStatus
         * @enum {string}
         */
        SourceStatus: "unreviewed" | "verified" | "disputed";
        /** Squad */
        Squad: {
            /** Days Since Full Squad */
            days_since_full_squad?: number | null;
            /** Matches Together */
            matches_together: number;
            /** Members */
            members: components["schemas"]["SquadMember"][];
            /** Squad Id */
            squad_id: string;
        };
        /** SquadMember */
        SquadMember: {
            /** Display Name */
            display_name: string;
            /**
             * Opted In
             * @default true
             */
            opted_in: boolean;
            /** Player Id */
            player_id: string;
            /** Role */
            role?: string | null;
        };
        /** SquadMemberV11 */
        SquadMemberV11: {
            /** Display Name */
            display_name: string;
            /** Opted In */
            opted_in: boolean;
            /** Player Id */
            player_id: string;
            /** Role */
            role?: string | null;
        };
        /** SquadV11 */
        SquadV11: {
            /** Days Since Full Squad */
            days_since_full_squad?: number | null;
            /** Matches Together */
            matches_together: number;
            /** Members */
            members: components["schemas"]["SquadMemberV11"][];
            /** Squad Id */
            squad_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationIssue */
        ValidationIssue: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            severity: components["schemas"]["IssueSeverity"];
        };
        /** ValidationReport */
        ValidationReport: {
            /** Human Review Required */
            human_review_required: boolean;
            /** Issues */
            issues?: components["schemas"]["ValidationIssue"][];
            /** Passed */
            passed: boolean;
            scores: components["schemas"]["QualityScores"];
        };
        /** VerificationRule */
        VerificationRule: {
            /** Metric */
            metric: string;
            /**
             * Operator
             * @enum {string}
             */
            operator: "equals" | "at_least" | "contains_all";
            /** Target */
            target: string | number | boolean | string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    discover_memory_v1_memories_discover_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LegacyMemoryPack"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryEngineResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderErrorBody"];
                };
            };
        };
    };
    discover_history_v1_memories_discover_history_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HistoricalDiscoveryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoricalDiscoveryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_memory_v1_memories_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateMemoryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryEngineResultV11"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderErrorBody"];
                };
            };
        };
    };
    generate_memory_stream_v1_memories_generate_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateMemoryRequest"];
            };
        };
        responses: {
            /** @description Newline-delimited generation events; the schema describes one line. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-ndjson": components["schemas"]["GenerateStreamStageEvent"] | components["schemas"]["GenerateStreamErrorEvent"] | components["schemas"]["GenerateStreamResultEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
