/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Discover Memory
         * @deprecated
         * @description Legacy v1.0 full-pipeline adapter retained during the migration window.
         */
        post: operations["discover_memory_v1_memories_discover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/discover-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Discover History
         * @description Rank historical candidates deterministically without model calls.
         */
        post: operations["discover_history_v1_memories_discover_history_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Memory
         * @deprecated
         * @description Expand a reviewed candidate into perspectives and a grounded quest.
         */
        post: operations["generate_memory_v1_memories_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/generate-stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Memory Stream
         * @deprecated
         * @description Expose the canonical generation result as newline-delimited stage events.
         */
        post: operations["generate_memory_stream_v1_memories_generate_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/prepare-delivery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Prepare Delivery
         * @deprecated
         * @description Prepare one trusted squad memory for an accept-or-decline delivery.
         */
        post: operations["prepare_delivery_v1_memories_prepare_delivery_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/record-delivery-decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Delivery Decision
         * @deprecated
         * @description Record a prototype accept/decline decision for a prepared delivery.
         */
        post: operations["record_delivery_decision_v1_memories_record_delivery_decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/deliveries/{delivery_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Delivery Decision V2
         * @description Capture exactly one prototype relevance decision for a validated v2 delivery.
         */
        post: operations["record_delivery_decision_v2_v2_deliveries__delivery_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/deliveries/{delivery_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Delivery Trace V2
         * @description Return a sanitized Studio trace, including the recorded player decision.
         */
        get: operations["get_delivery_trace_v2_v2_deliveries__delivery_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/memories/interpret-delivery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Interpret Delivery V2
         * @description Interpret telemetry into one fully validated player delivery or fail closed.
         */
        post: operations["interpret_delivery_v2_v2_memories_interpret_delivery_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CandidateScoreBreakdown
         * @description Weighted eligibility contributions; total excludes the ranking-only penalty.
         */
        CandidateScoreBreakdown: {
            /**
             * Diversity Penalty
             * @default 0
             */
            diversity_penalty: number;
            /** Evidence Strength */
            evidence_strength: number;
            /** Human Signals */
            human_signals: number;
            /** Resurfacing Relevance */
            resurfacing_relevance: number;
            /** Squad Specificity */
            squad_specificity: number;
            /** Total */
            total: number;
        };
        /**
         * ClaimPredicate
         * @enum {string}
         */
        ClaimPredicate: "participated_match" | "played_mode" | "played_map" | "placed" | "match_result" | "landed" | "knocked" | "was_knocked" | "eliminated" | "was_eliminated" | "revived" | "assisted" | "healed" | "entered_vehicle" | "exited_vehicle" | "escaped" | "moved_zone" | "looted" | "signalled" | "completed_match" | "connected_episode" | "current_reunion_opportunity" | "mission_rule";
        /** ConsentPermissionsV2 */
        ConsentPermissionsV2: {
            /** Identity Display */
            identity_display: boolean;
            /** Media Use */
            media_use: boolean;
            /** Memory Appearance */
            memory_appearance: boolean;
            /** Mission Invitation */
            mission_invitation: boolean;
        };
        /** CurrentContext */
        CurrentContext: {
            /** Active Member Ids */
            active_member_ids?: string[];
            /**
             * Original Mode Available
             * @default true
             */
            original_mode_available: boolean;
            /** Resurfacing Reason */
            resurfacing_reason?: string | null;
        };
        /** CurrentContextV2 */
        CurrentContextV2: {
            /** Active Player Ids */
            active_player_ids?: string[];
            /** Available Modes */
            available_modes?: string[];
            /**
             * Reunion Eligible
             * @default true
             */
            reunion_eligible: boolean;
        };
        /**
         * DeliveryDecision
         * @enum {string}
         */
        DeliveryDecision: "accepted" | "declined";
        /** DeliveryDecisionRecordV2 */
        DeliveryDecisionRecordV2: {
            decision: components["schemas"]["DeliveryDecision"];
            decline_reason?: components["schemas"]["DeliveryDeclineReason"] | null;
            /** Delivery Id */
            delivery_id: string;
            /**
             * Delivery Status
             * @enum {string}
             */
            delivery_status: "mission_started" | "suppressed";
            /**
             * Schema Version
             * @default 2.0
             * @constant
             */
            schema_version: "2.0";
            /** Source Quality Flag */
            source_quality_flag: boolean;
        };
        /**
         * DeliveryDeclineReason
         * @enum {string}
         */
        DeliveryDeclineReason: "not_relevant" | "details_wrong";
        /** DeliveryMemoryV2 */
        DeliveryMemoryV2: {
            media_reference?: components["schemas"]["MediaReferenceV2"] | null;
            memory_type: components["schemas"]["MemoryType"];
            /** Notification Teaser */
            notification_teaser: string;
            /** Selected Event Ids */
            selected_event_ids: string[];
            /** Selected Match Id */
            selected_match_id: string;
            /** Summary */
            summary: string;
            /** Title */
            title: string;
            /** Why This Matters Now */
            why_this_matters_now: string;
        };
        /** DeliveryMissionObjectiveV2 */
        DeliveryMissionObjectiveV2: {
            /** Assigned Player Id */
            assigned_player_id?: string | null;
            /** Description */
            description: string;
            /** Objective Id */
            objective_id: string;
            /** Required */
            required: boolean;
            /** Source Event Ids */
            source_event_ids: string[];
            verification: components["schemas"]["VerificationRule"];
        };
        /** DeliveryNarrative */
        DeliveryNarrative: {
            /** Teaser */
            teaser: string;
            /** Why This Surfaced */
            why_this_surfaced: string;
        };
        /** DeliveryNextChapterV2 */
        DeliveryNextChapterV2: {
            /** Mission */
            mission: string;
            /** Objectives */
            objectives: components["schemas"]["DeliveryMissionObjectiveV2"][];
            recipe: components["schemas"]["QuestRecipe"];
            /** Title */
            title: string;
        };
        /** DeliveryPerspectiveV2 */
        DeliveryPerspectiveV2: {
            /** Display Name */
            display_name: string;
            /** Evidence Event Ids */
            evidence_event_ids: string[];
            /** Message */
            message: string;
            /** Player Id */
            player_id: string;
        };
        /**
         * DeliveryStatus
         * @enum {string}
         */
        DeliveryStatus: "pending_player_decision" | "rejected";
        /** DiscoveryAssessment */
        DiscoveryAssessment: {
            /** Eligible */
            eligible: boolean;
            /** Reasons */
            reasons: string[];
            /** Signal Score */
            signal_score: number;
            /** Threshold */
            threshold: number;
        };
        /** EligibleEventWindow */
        EligibleEventWindow: {
            /** End Seconds */
            end_seconds: number;
            /** Event Ids */
            event_ids: string[];
            /** Match Id */
            match_id: string;
            /** Participant Ids */
            participant_ids?: string[];
            /** Start Seconds */
            start_seconds: number;
            /** Window Id */
            window_id: string;
        };
        /** EvidenceRef */
        EvidenceRef: {
            /** Event Id */
            event_id: string;
            /** Event Type */
            event_type: string;
            /** Significance */
            significance: string;
        };
        /** GenerateMemoryRequest */
        GenerateMemoryRequest: {
            /** Memory Pack */
            memory_pack: components["schemas"]["MemoryPack"] | components["schemas"]["MemoryPackV11"];
            /**
             * Schema Version
             * @default 1.1
             * @constant
             */
            schema_version: "1.1";
        };
        /**
         * GenerateStreamErrorEvent
         * @description A safe provider failure emitted after an NDJSON stream has begun.
         */
        GenerateStreamErrorEvent: {
            /** Code */
            code: string;
            /** Retryable */
            retryable: boolean;
            /** Stage */
            stage: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "error";
        };
        /**
         * GenerateStreamResultEvent
         * @description The canonical v1.1 result emitted as the final NDJSON record.
         */
        GenerateStreamResultEvent: {
            result: components["schemas"]["MemoryEngineResultV11"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "result";
        };
        /**
         * GenerateStreamStageEvent
         * @description One progress snapshot in the NDJSON generation stream.
         */
        GenerateStreamStageEvent: {
            /** Message */
            message?: string | null;
            /** Observability */
            observability?: {
                [key: string]: unknown;
            } | null;
            /** Preview */
            preview?: components["schemas"]["MemoryRecord"] | components["schemas"]["PlayerPerspective"][] | components["schemas"]["NextChapter"] | components["schemas"]["ValidationReport"] | null;
            /**
             * Stage
             * @enum {string}
             */
            stage: "review_and_discovery" | "memory_discovery" | "perspectives" | "quest_generation" | "validation";
            /**
             * Status
             * @enum {string}
             */
            status: "working" | "complete" | "stopped" | "failed";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "stage";
        };
        /** GroundedClaim */
        GroundedClaim: {
            /** Claim Id */
            claim_id: string;
            /** Location */
            location?: string | null;
            /** Output Section */
            output_section: string;
            predicate: components["schemas"]["ClaimPredicate"];
            /** Subject Id */
            subject_id: string;
            /** Supporting Context Ids */
            supporting_context_ids?: string[];
            /** Supporting Event Ids */
            supporting_event_ids?: string[];
            /** Supporting Mission Candidate Ids */
            supporting_mission_candidate_ids?: string[];
            /** Target Id */
            target_id?: string | null;
            /** Value */
            value?: string | number | boolean | string[] | null;
            /** Value Key */
            value_key?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoricalCandidate */
        HistoricalCandidate: {
            /** Match Id */
            match_id: string;
            meaning_status: components["schemas"]["MeaningStatus"];
            memory_type: components["schemas"]["MemoryType"];
            /** Pack Id */
            pack_id: string;
            /** Rank */
            rank: number;
            /** Ranking Score */
            ranking_score: number;
            /** Reasons */
            reasons: string[];
            /** Redactions */
            redactions?: components["schemas"]["RedactionNotice"][];
            /** Score */
            score: number;
            score_breakdown: components["schemas"]["CandidateScoreBreakdown"];
            source_status: components["schemas"]["SourceStatus"];
            /** Summary */
            summary: string;
            /** Title */
            title: string;
        };
        /** HistoricalDiscoveryRequest */
        HistoricalDiscoveryRequest: {
            /**
             * Limit
             * @default 3
             */
            limit: number;
            /** Memory Packs */
            memory_packs: (components["schemas"]["MemoryPack"] | components["schemas"]["MemoryPackV11"])[];
            /**
             * Schema Version
             * @default 1.1
             * @constant
             */
            schema_version: "1.1";
        };
        /** HistoricalDiscoveryResponse */
        HistoricalDiscoveryResponse: {
            /** Candidates */
            candidates: components["schemas"]["HistoricalCandidate"][];
            filters: components["schemas"]["HistoricalFilterCounts"];
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Schema Version
             * @default 1.1
             * @constant
             */
            schema_version: "1.1";
        };
        /** HistoricalFilterCounts */
        HistoricalFilterCounts: {
            /** Below Threshold */
            below_threshold: number;
            /** Dismissed */
            dismissed: number;
            /** Disputed */
            disputed: number;
            /** Duplicates Removed */
            duplicates_removed: number;
            /** Eligible Not Selected */
            eligible_not_selected: number;
            /** Insufficient Opted In */
            insufficient_opted_in: number;
            /** No Grounded Events */
            no_grounded_events: number;
            /** Received */
            received: number;
            /** Target Opted Out */
            target_opted_out: number;
        };
        /** HumanMemory */
        HumanMemory: {
            /** Author Player Id */
            author_player_id?: string | null;
            /** Caption */
            caption?: string | null;
            /** Confirmed */
            confirmed?: boolean | null;
            /** Tags */
            tags?: string[];
        };
        /** HumanMemoryV11 */
        HumanMemoryV11: {
            /** Author Player Id */
            author_player_id?: string | null;
            /** Caption */
            caption?: string | null;
            /** Tags */
            tags?: string[];
        };
        /**
         * HumanReview
         * @description Separate factual verification from a player's emotional judgment.
         */
        HumanReview: {
            /** @default unreviewed */
            meaning_status: components["schemas"]["MeaningStatus"];
            /** @default unreviewed */
            source_status: components["schemas"]["SourceStatus"];
        };
        /**
         * Importance
         * @enum {string}
         */
        Importance: "low" | "medium" | "high";
        /** InterpretDeliveryResultV2 */
        InterpretDeliveryResultV2: {
            /** Delivery Id */
            delivery_id?: string | null;
            /** Grounded Claims */
            grounded_claims?: components["schemas"]["GroundedClaim"][];
            memory?: components["schemas"]["DeliveryMemoryV2"] | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            next_chapter?: components["schemas"]["DeliveryNextChapterV2"] | null;
            /** Player Perspectives */
            player_perspectives?: components["schemas"]["DeliveryPerspectiveV2"][];
            /** Reason Codes */
            reason_codes?: string[];
            /** Request Id */
            request_id: string;
            /**
             * Schema Version
             * @default 2.0
             * @constant
             */
            schema_version: "2.0";
            status: components["schemas"]["InterpretDeliveryStatusV2"];
            studio_trace: components["schemas"]["StudioInterpretationTraceV2"];
            validation: components["schemas"]["ProposalValidationReportV2"];
        };
        /**
         * InterpretDeliveryStatusV2
         * @enum {string}
         */
        InterpretDeliveryStatusV2: "pending_player_decision" | "rejected";
        /**
         * IssueSeverity
         * @enum {string}
         */
        IssueSeverity: "info" | "warning" | "error";
        /**
         * LegacyMemoryPack
         * @description The deprecated endpoint accepts only the original v1.0 wire contract.
         */
        LegacyMemoryPack: {
            current_context?: components["schemas"]["CurrentContext"];
            human_memory?: components["schemas"]["HumanMemory"] | null;
            match: components["schemas"]["MatchContext"];
            /** Match Events */
            match_events?: components["schemas"]["MatchEvent"][];
            /** Pack Id */
            pack_id: string;
            player_profile: components["schemas"]["PlayerProfile"];
            reactions?: components["schemas"]["Reactions"];
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            squad: components["schemas"]["LegacySquad"];
        };
        /**
         * LegacySquad
         * @description The legacy wire shape with current consent made explicit.
         */
        LegacySquad: {
            /** Days Since Full Squad */
            days_since_full_squad?: number | null;
            /** Matches Together */
            matches_together: number;
            /** Members */
            members: components["schemas"]["LegacySquadMember"][];
            /** Squad Id */
            squad_id: string;
        };
        /**
         * LegacySquadMember
         * @description A v1.0 member submitted through the public compatibility endpoint.
         */
        LegacySquadMember: {
            /** Display Name */
            display_name: string;
            /** Opted In */
            opted_in: boolean;
            /** Player Id */
            player_id: string;
            /** Role */
            role?: string | null;
        };
        /** MatchContext */
        MatchContext: {
            /** Map Name */
            map_name?: string | null;
            /** Match Id */
            match_id: string;
            /** Mode */
            mode: string;
            /** Placement */
            placement?: number | null;
            /** Played At */
            played_at?: string | null;
        };
        /** MatchEvent */
        MatchEvent: {
            /** Actor Id */
            actor_id?: string | null;
            /** Details */
            details?: {
                [key: string]: string | number | boolean;
            };
            /** Event Id */
            event_id: string;
            /** @default medium */
            importance: components["schemas"]["Importance"];
            /** Location */
            location?: string | null;
            /** Target Id */
            target_id?: string | null;
            /** Timestamp Seconds */
            timestamp_seconds?: number | null;
            /** Type */
            type: string;
        };
        /**
         * MeaningStatus
         * @enum {string}
         */
        MeaningStatus: "unreviewed" | "confirmed" | "dismissed";
        /** MediaReferenceV2 */
        MediaReferenceV2: {
            /** Consented Player Ids */
            consented_player_ids?: string[];
            /** Event Ids */
            event_ids: string[];
            /**
             * Kind
             * @enum {string}
             */
            kind: "clip" | "thumbnail" | "keyframe";
            /** Media Id */
            media_id: string;
        };
        /** MemoryDeliveryResult */
        MemoryDeliveryResult: {
            /** Delivery Id */
            delivery_id?: string | null;
            meaning_status: components["schemas"]["MeaningStatus"];
            memory?: components["schemas"]["MemoryRecord"] | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            narrative?: components["schemas"]["DeliveryNarrative"] | null;
            next_chapter?: components["schemas"]["NextChapter"] | null;
            /** Pack Id */
            pack_id: string;
            /** Player Perspectives */
            player_perspectives?: components["schemas"]["PlayerPerspective"][];
            /**
             * Schema Version
             * @default 1.1
             * @constant
             */
            schema_version: "1.1";
            source_status: components["schemas"]["SourceStatus"];
            status: components["schemas"]["DeliveryStatus"];
            validation: components["schemas"]["ValidationReport"];
        };
        /** MemoryEngineResult */
        MemoryEngineResult: {
            discovery: components["schemas"]["DiscoveryAssessment"];
            memory?: components["schemas"]["MemoryRecord"] | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            next_chapter?: components["schemas"]["NextChapter"] | null;
            /** Pack Id */
            pack_id: string;
            /** Player Perspectives */
            player_perspectives?: components["schemas"]["PlayerPerspective"][];
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            status: components["schemas"]["PipelineStatus"];
            validation: components["schemas"]["ValidationReport"];
        };
        /** MemoryEngineResultV11 */
        MemoryEngineResultV11: {
            discovery: components["schemas"]["DiscoveryAssessment"];
            meaning_status: components["schemas"]["MeaningStatus"];
            memory?: components["schemas"]["MemoryRecord"] | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            next_chapter?: components["schemas"]["NextChapter"] | null;
            /** Pack Id */
            pack_id: string;
            /** Player Perspectives */
            player_perspectives?: components["schemas"]["PlayerPerspective"][];
            /**
             * Schema Version
             * @default 1.1
             * @constant
             */
            schema_version: "1.1";
            source_status: components["schemas"]["SourceStatus"];
            status: components["schemas"]["PipelineStatusV11"];
            validation: components["schemas"]["ValidationReport"];
        };
        /**
         * MemoryPack
         * @description Garena-style input: gameplay, social, human, and current context signals.
         */
        MemoryPack: {
            current_context?: components["schemas"]["CurrentContext"];
            human_memory?: components["schemas"]["HumanMemory"] | null;
            match: components["schemas"]["MatchContext"];
            /** Match Events */
            match_events?: components["schemas"]["MatchEvent"][];
            /** Pack Id */
            pack_id: string;
            player_profile: components["schemas"]["PlayerProfile"];
            reactions?: components["schemas"]["Reactions"];
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            squad: components["schemas"]["Squad"];
        };
        /**
         * MemoryPackV11
         * @description Canonical Phase 2 input with explicit consent and split review state.
         */
        MemoryPackV11: {
            current_context?: components["schemas"]["CurrentContext"];
            human_memory?: components["schemas"]["HumanMemoryV11"] | null;
            human_review: components["schemas"]["HumanReview"];
            match: components["schemas"]["MatchContext"];
            /** Match Events */
            match_events?: components["schemas"]["MatchEvent"][];
            /** Pack Id */
            pack_id: string;
            player_profile: components["schemas"]["PlayerProfile"];
            reactions?: components["schemas"]["Reactions"];
            /**
             * Schema Version
             * @default 1.1
             * @constant
             */
            schema_version: "1.1";
            squad: components["schemas"]["SquadV11"];
        };
        /** MemoryRecord */
        MemoryRecord: {
            /** Confidence */
            confidence: number;
            /** Evidence */
            evidence: components["schemas"]["EvidenceRef"][];
            /** Human Confirmed */
            human_confirmed: boolean;
            memory_type: components["schemas"]["MemoryType"];
            /** Summary */
            summary: string;
            /** Title */
            title: string;
        };
        /**
         * MemoryType
         * @enum {string}
         */
        MemoryType: "chaos" | "comeback" | "clutch" | "ritual" | "first" | "other";
        /** MissionCapabilityCandidate */
        MissionCapabilityCandidate: {
            /** Assigned Player Id */
            assigned_player_id?: string | null;
            /** Candidate Id */
            candidate_id: string;
            recipe: components["schemas"]["QuestRecipe"];
            /** Source Event Ids */
            source_event_ids: string[];
            verification: components["schemas"]["VerificationRule"];
            /** Window Id */
            window_id: string;
        };
        /** NextChapter */
        NextChapter: {
            /** Mission */
            mission: string;
            /** Objectives */
            objectives: components["schemas"]["QuestObjective"][];
            recipe: components["schemas"]["QuestRecipe"];
            /** Title */
            title: string;
        };
        /**
         * PipelineStatus
         * @enum {string}
         */
        PipelineStatus: "ready" | "needs_human_confirmation" | "rejected";
        /**
         * PipelineStatusV11
         * @enum {string}
         */
        PipelineStatusV11: "ready" | "needs_source_verification" | "needs_meaning_confirmation" | "rejected";
        /** PlayerPerspective */
        PlayerPerspective: {
            /** Display Name */
            display_name: string;
            /** Evidence Event Ids */
            evidence_event_ids: string[];
            /** Message */
            message: string;
            /** Player Id */
            player_id: string;
        };
        /** PlayerProfile */
        PlayerProfile: {
            /** Player Id */
            player_id: string;
            /** Preferred Role */
            preferred_role?: string | null;
        };
        /**
         * PrepareDeliveryRequest
         * @description Prepare the strongest trusted moment for a player-facing delivery.
         */
        PrepareDeliveryRequest: {
            /** Memory Packs */
            memory_packs: components["schemas"]["MemoryPackV11"][];
            /**
             * Schema Version
             * @default 1.1
             * @constant
             */
            schema_version: "1.1";
        };
        /** ProposalValidationReportV2 */
        ProposalValidationReportV2: {
            /**
             * Correction Attempted
             * @default false
             */
            correction_attempted: boolean;
            /** Issues */
            issues?: components["schemas"]["V2ValidationIssue"][];
            /** Passed */
            passed: boolean;
        };
        /** ProviderErrorBody */
        ProviderErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Retryable */
            retryable: boolean;
            /** Stage */
            stage: string;
        };
        /** QualityScores */
        QualityScores: {
            /** Evidence Grounding */
            evidence_grounding: number;
            /** Perspective Distinctness */
            perspective_distinctness: number;
            /** Quest Connection */
            quest_connection: number;
            /** Specificity */
            specificity: number;
        };
        /** QuestObjective */
        QuestObjective: {
            /** Assigned Player Id */
            assigned_player_id?: string | null;
            /** Description */
            description: string;
            /** Objective Id */
            objective_id: string;
            /** Required */
            required: boolean;
            /** Source Event Ids */
            source_event_ids: string[];
            verification: components["schemas"]["VerificationRule"];
        };
        /**
         * QuestRecipe
         * @enum {string}
         */
        QuestRecipe: "recreate" | "remix" | "resolve";
        /** RawMatchV2 */
        RawMatchV2: {
            /** Ended At */
            ended_at?: string | null;
            /** Events */
            events: components["schemas"]["RawTelemetryEventV2"][];
            /** Game */
            game: string;
            /** Map Name */
            map_name?: string | null;
            /** Match Id */
            match_id: string;
            /** Mode */
            mode: string;
            /** Placement */
            placement?: number | null;
            /** Result */
            result?: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
        };
        /** RawPlayerV2 */
        RawPlayerV2: {
            consent: components["schemas"]["ConsentPermissionsV2"];
            /** Display Name */
            display_name?: string | null;
            /** Player Id */
            player_id: string;
        };
        /** RawSquadV2 */
        RawSquadV2: {
            /** Players */
            players: components["schemas"]["RawPlayerV2"][];
            /** Squad Id */
            squad_id: string;
        };
        /**
         * RawTelemetryBatchV2
         * @description Realistic telemetry-only input. Unknown/pre-authored fields fail validation.
         */
        RawTelemetryBatchV2: {
            current_context?: components["schemas"]["CurrentContextV2"];
            /** Matches */
            matches: components["schemas"]["RawMatchV2"][];
            /** Media References */
            media_references?: components["schemas"]["MediaReferenceV2"][];
            /** Request Id */
            request_id: string;
            /**
             * Schema Version
             * @default 2.0
             * @constant
             */
            schema_version: "2.0";
            social_context?: components["schemas"]["SocialContextV2"] | null;
            squad: components["schemas"]["RawSquadV2"];
            squad_history?: components["schemas"]["SquadHistoryV2"];
            /** Target Player Id */
            target_player_id: string;
        };
        /** RawTelemetryEventV2 */
        RawTelemetryEventV2: {
            /** Actor Id */
            actor_id?: string | null;
            /** Details */
            details?: {
                [key: string]: string | number | boolean | string[];
            };
            /** Event Id */
            event_id: string;
            /** Location */
            location?: string | null;
            /** Provider Event Type */
            provider_event_type: string;
            /** Target Id */
            target_id?: string | null;
            /** Timestamp Seconds */
            timestamp_seconds: number;
        };
        /** Reactions */
        Reactions: {
            /**
             * Fire Count
             * @default 0
             */
            fire_count: number;
            /**
             * Laugh Count
             * @default 0
             */
            laugh_count: number;
            /**
             * Saved
             * @default false
             */
            saved: boolean;
        };
        /** RecordDeliveryDecisionRequest */
        RecordDeliveryDecisionRequest: {
            decision: components["schemas"]["DeliveryDecision"];
            decline_reason?: components["schemas"]["DeliveryDeclineReason"] | null;
            /** Delivery Id */
            delivery_id: string;
        };
        /** RecordDeliveryDecisionRequestV2 */
        RecordDeliveryDecisionRequestV2: {
            decision: components["schemas"]["DeliveryDecision"];
            decline_reason?: components["schemas"]["DeliveryDeclineReason"] | null;
            /**
             * Schema Version
             * @default 2.0
             * @constant
             */
            schema_version: "2.0";
        };
        /** RecordDeliveryDecisionResponse */
        RecordDeliveryDecisionResponse: {
            decision: components["schemas"]["DeliveryDecision"];
            decline_reason?: components["schemas"]["DeliveryDeclineReason"] | null;
            /** Delivery Id */
            delivery_id: string;
        };
        /** RedactionNotice */
        RedactionNotice: {
            /** Alias */
            alias: string;
            /**
             * Reason
             * @default player_opted_out
             * @constant
             */
            reason: "player_opted_out";
        };
        /** SocialContextV2 */
        SocialContextV2: {
            /** Caption Author Player Id */
            caption_author_player_id?: string | null;
            /** Event Tags */
            event_tags?: string[];
            /** Player Caption */
            player_caption?: string | null;
            /** Reaction Counts */
            reaction_counts?: {
                [key: string]: number;
            };
            /**
             * Saved Clip
             * @default false
             */
            saved_clip: boolean;
        };
        /**
         * SourceStatus
         * @enum {string}
         */
        SourceStatus: "unreviewed" | "verified" | "disputed";
        /** Squad */
        Squad: {
            /** Days Since Full Squad */
            days_since_full_squad?: number | null;
            /** Matches Together */
            matches_together: number;
            /** Members */
            members: components["schemas"]["SquadMember"][];
            /** Squad Id */
            squad_id: string;
        };
        /** SquadHistoryV2 */
        SquadHistoryV2: {
            /** Days Since Full Squad */
            days_since_full_squad?: number | null;
            /** Previous Session At */
            previous_session_at?: string[];
            /**
             * Recent Rematch Count
             * @default 0
             */
            recent_rematch_count: number;
        };
        /** SquadMember */
        SquadMember: {
            /** Display Name */
            display_name: string;
            /**
             * Opted In
             * @default true
             */
            opted_in: boolean;
            /** Player Id */
            player_id: string;
            /** Role */
            role?: string | null;
        };
        /** SquadMemberV11 */
        SquadMemberV11: {
            /** Display Name */
            display_name: string;
            /** Opted In */
            opted_in: boolean;
            /** Player Id */
            player_id: string;
            /** Role */
            role?: string | null;
        };
        /** SquadV11 */
        SquadV11: {
            /** Days Since Full Squad */
            days_since_full_squad?: number | null;
            /** Matches Together */
            matches_together: number;
            /** Members */
            members: components["schemas"]["SquadMemberV11"][];
            /** Squad Id */
            squad_id: string;
        };
        /** StudioClaimTraceV2 */
        StudioClaimTraceV2: {
            /** Claim Id */
            claim_id: string;
            /** Evidence Ids */
            evidence_ids: string[];
            /** Output Section */
            output_section: string;
            predicate: components["schemas"]["ClaimPredicate"];
        };
        /** StudioInterpretationTraceV2 */
        StudioInterpretationTraceV2: {
            /** Claim Mappings */
            claim_mappings?: components["schemas"]["StudioClaimTraceV2"][];
            /**
             * Correction Attempted
             * @default false
             */
            correction_attempted: boolean;
            /** Eligible Windows */
            eligible_windows?: components["schemas"]["EligibleEventWindow"][];
            /** Mission Candidates */
            mission_candidates?: components["schemas"]["MissionCapabilityCandidate"][];
            /** Normalized Event Count */
            normalized_event_count: number;
            /** Normalized Match Count */
            normalized_match_count: number;
            /** Privacy Redaction Count */
            privacy_redaction_count: number;
            /**
             * Source Quality Flag
             * @default false
             */
            source_quality_flag: boolean;
            /** Stages */
            stages: components["schemas"]["StudioTraceStageV2"][];
            /** Trace Id */
            trace_id: string;
        };
        /** StudioTraceStageV2 */
        StudioTraceStageV2: {
            /** Issue Codes */
            issue_codes?: string[];
            /**
             * Stage
             * @enum {string}
             */
            stage: "deterministic_preparation" | "ai_interpretation" | "deterministic_validation" | "player_decision";
            /**
             * Status
             * @enum {string}
             */
            status: "complete" | "rejected" | "withheld" | "pending";
            /** Summary */
            summary: string;
        };
        /** V2ValidationIssue */
        V2ValidationIssue: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "warning" | "error";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationIssue */
        ValidationIssue: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            severity: components["schemas"]["IssueSeverity"];
        };
        /** ValidationReport */
        ValidationReport: {
            /** Human Review Required */
            human_review_required: boolean;
            /** Issues */
            issues?: components["schemas"]["ValidationIssue"][];
            /** Passed */
            passed: boolean;
            scores: components["schemas"]["QualityScores"];
        };
        /** VerificationRule */
        VerificationRule: {
            /** Metric */
            metric: string;
            /**
             * Operator
             * @enum {string}
             */
            operator: "equals" | "at_least" | "contains_all";
            /** Target */
            target: string | number | boolean | string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    discover_memory_v1_memories_discover_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LegacyMemoryPack"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryEngineResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderErrorBody"];
                };
            };
        };
    };
    discover_history_v1_memories_discover_history_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HistoricalDiscoveryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoricalDiscoveryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_memory_v1_memories_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateMemoryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryEngineResultV11"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderErrorBody"];
                };
            };
        };
    };
    generate_memory_stream_v1_memories_generate_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateMemoryRequest"];
            };
        };
        responses: {
            /** @description Newline-delimited generation events; the schema describes one line. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-ndjson": components["schemas"]["GenerateStreamStageEvent"] | components["schemas"]["GenerateStreamErrorEvent"] | components["schemas"]["GenerateStreamResultEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prepare_delivery_v1_memories_prepare_delivery_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrepareDeliveryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryDeliveryResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderErrorBody"];
                };
            };
        };
    };
    record_delivery_decision_v1_memories_record_delivery_decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordDeliveryDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordDeliveryDecisionResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_delivery_decision_v2_v2_deliveries__delivery_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                delivery_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordDeliveryDecisionRequestV2"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryDecisionRecordV2"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_delivery_trace_v2_v2_deliveries__delivery_id__trace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                delivery_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudioInterpretationTraceV2"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    interpret_delivery_v2_v2_memories_interpret_delivery_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RawTelemetryBatchV2"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterpretDeliveryResultV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderErrorBody"];
                };
            };
        };
    };
}
